comment:
  behavior: default
  layout: reach, diff, flags, files
  require_changes:
  - 0
coverage:
  precision: 2
  range:
  - 70.0
  - 90.0
  round: down
  status:
    patch:
      default:
        target: 75.0
        threshold: 5.0
    project:
      default:
        if_ci_failed: error
        target: 80.0
        threshold: 1.0
github_checks:
  annotations: true
