name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Backend tests
        run: npm test --prefix packages/express-backend

      - name: Frontend tests
        run: npm test --prefix packages/react-frontend

  codeql-init:
    name: Initialize CodeQL
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.init.outputs.languages }}
    steps:
      - uses: actions/checkout@v3
      - id: init
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

  codeql-analyze:
    name:
      CodeQL / Analyze (${{ needs.codeql-init.outputs.languages }}) (dynamic)
    needs: codeql-init
    runs-on: ubuntu-latest
    steps:
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
