name: CI

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Backend tests
        run: npm test --prefix packages/express-backend

      - name: Frontend tests
        run: npm test --prefix packages/react-frontend

  codeql-analysis:
    name:
      CodeQL / Analyze (${{ needs.codeql-analysis.outputs.languages }})
      (dynamic)
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: init
        name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: actions,javascript

      - name: Install & build for CodeQL
        run: |
          npm ci
          npm run build --workspace react-frontend

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
