name: CI

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: npm ci

      - name: Ensure Rollup dependencies for Linux
        run: |
          npm install --no-save @rollup/rollup-linux-x64-gnu
        if: runner.os == 'Linux'

      - name: Lint
        run: npm run lint

      - name: Verify Vite build
        run: |
          cd packages/react-frontend
          npm run build
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_REGION: ${{ secrets.S3_REGION }}

      - name: Backend tests with coverage
        run: npm --prefix packages/express-backend test -- --coverage

      - name: Frontend tests with coverage
        run: npm --prefix packages/react-frontend test -- --coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports-${{ matrix.node-version }}
          path: |
            packages/express-backend/coverage
            packages/react-frontend/coverage

  codeql-analysis:
    name: CodeQL Analysis
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: init
        name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Install & build for CodeQL
        run: |
          npm ci
          npm install --no-save @rollup/rollup-linux-x64-gnu
          npm run build --workspace react-frontend

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
